spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sa
    username: ehyeon
    password: ehyeon
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
